project_name: zap-pretty

release:
  github:
    owner: maoueh
    name: zap-pretty
  name_template: '{{.Tag}}'
builds:
  - id: zap-pretty
    goos:
    - linux
    - darwin
    - windows
    goarch:
    - arm64
    - amd64
    targets:
    - linux_amd64
    - darwin_amd64
    - darwin_arm64
    - windows_amd64
    main: ./
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: zap-pretty
    env:
    - CGO_ENABLED=0

archives:
  # sfeth
  - name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    id: zap-pretty
    builds:
    - zap-pretty
    replacements:
      amd64: x86_64
      darwin: macOS
      linux: linux
    format: tar.gz
    files:
    - LICENSE.md
    - README.md

snapshot:
  name_template: '{{ .Tag }}-next'

checksum:
  name_template: checksums.txt

changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
  sort: asc

dist: dist

signs:
- cmd: keybase
  args:
  - sign
  - --infile
  - $artifact
  - --binary
  - --outfile
  - $signature
  - --detached
  signature: ${artifact}.sig
  artifacts: checksum
env_files:
  github_token: ~/.config/goreleaser/github_token
brews:
  - name: zap-pretty
    ids:
    - zap-pretty
    tap:
      owner: maoueh
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: matthieu.o.vachon@gmail.com
    homepage: "https://github.com/maoueh/zap-pretty"
    description: "A tiny binary to pretty-print Zap production JSON lines"
    license: "MIT"

