# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZapPretty < Formula
  desc ""
  homepage "https://github.com/maoueh/zap-pretty"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/maoueh/zap-pretty/releases/download/v0.3.1/zap-pretty_darwin_x86_64.tar.gz"
      sha256 "5456f8d87dc62caaa5da55f3388c1af1a1e65c09de457c5709cf97c417948e58"

      def install
        bin.install "zap-pretty"
      end
    end
    on_arm do
      url "https://github.com/maoueh/zap-pretty/releases/download/v0.3.1/zap-pretty_darwin_arm64.tar.gz"
      sha256 "f32e34de0477eb852e8fccee641bb0b7857f54bf26ef26ff42309ec538561de6"

      def install
        bin.install "zap-pretty"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/maoueh/zap-pretty/releases/download/v0.3.1/zap-pretty_linux_x86_64.tar.gz"
        sha256 "830f785d72b40ecd76547e78ae4978846cdc7a57b39593fb58cba0bae9afee21"

        def install
          bin.install "zap-pretty"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/maoueh/zap-pretty/releases/download/v0.3.1/zap-pretty_linux_arm64.tar.gz"
        sha256 "5d917a120626e942376be9140272be9b5f8796d4090c6e9bd1f20493b2a5e820"

        def install
          bin.install "zap-pretty"
        end
      end
    end
  end
end
